routes/admin.php
    Route::get('admin-control/reset-password', 'admin\ResetpasswordController@index');

Route::group(['prefix' => 'admin-control', 'middleware' => 'guest'], function() {
    Route::get( '/', [ 'as' => 'login', 'uses' => 'admin\UserController@login'] );
    Route::post( 'login-auth', 'admin\UserController@auth' );
});

// Logout

Route::group(['prefix' => 'admin-control', 'middleware' => 'auth'], function() {
    Route::get( 'logout', 'admin\UserController@logout' );
    Route::get( 'dashboard', ['as' => 'home', 'uses' => 'admin\DashboardController@index' ]  );

// dashboard

    Route::get('dashboard','admin\DashboardController@index');
    Route::get('/inquiry','admin\InquiryController@index');
    Route::get('inquiry/remove/{id}','admin\InquiryController@remove');
    Route::post('inquiry/removeMultiple','admin\InquiryController@removeMultiple');
    
Route::get('/clear-cache', function() {
    $exitCode = Artisan::call('cache:clear');
    return 'clearede';
});



// Marquee-img

    Route::get('marquee-img', 'admin\MarqueeController@index');    
    Route::get('marquee-img/add','admin\MarqueeController@add');
    Route::post('marquee-img/add','admin\MarqueeController@adddata');
    Route::get('marquee-img/edit/{id}', 'admin\MarqueeController@edit');
    Route::post('marquee-img/edit/{id}', 'admin\MarqueeController@editdata');
    Route::get('marquee-img/remove/{id}','admin\MarqueeController@remove');
    Route::post('marquee-img/removeMultiple','admin\MarqueeController@removeMultiple');


// Unit

    Route::get('unit', 'admin\UnitController@index');    
    Route::get('unit/add','admin\UnitController@add');
    Route::post('unit/add','admin\UnitController@adddata');
    Route::get('unit/edit/{id}', 'admin\UnitController@edit');
    Route::post('unit/edit/{id}', 'admin\UnitController@editdata');
    Route::get('unit/remove/{id}','admin\UnitController@remove');
    Route::post('unit/removeMultiple','admin\UnitController@removeMultiple'); 

// Unit

    Route::get('coupon', 'admin\CouponController@index');    
    Route::get('coupon/add','admin\CouponController@add');
    Route::post('coupon/add','admin\CouponController@adddata');
    Route::get('coupon/edit/{id}', 'admin\CouponController@edit');
    Route::post('coupon/edit/{id}', 'admin\CouponController@editdata');
    Route::get('coupon/remove/{id}','admin\CouponController@remove');
    Route::post('coupon/removeMultiple','admin\CouponController@removeMultiple'); 

// City

    Route::get('city', 'admin\CityController@index');    
    Route::get('city/add','admin\CityController@add');
    Route::post('city/add','admin\CityController@adddata');
    Route::get('city/edit/{id}', 'admin\CityController@edit');
    Route::post('city/edit/{id}', 'admin\CityController@editdata');
    Route::get('city/remove/{id}','admin\CityController@remove');
    Route::post('city/removeMultiple','admin\CityController@removeMultiple'); 

// Vendor

    Route::get('vendor', 'admin\VendorController@index');    
    Route::get('vendor/add','admin\VendorController@add');
    Route::post('vendor/add','admin\VendorController@adddata');
    Route::get('vendor/edit/{id}', 'admin\VendorController@edit');
    Route::post('vendor/edit/{id}', 'admin\VendorController@editdata');
    Route::get('vendor/remove/{id}','admin\VendorController@remove');
    Route::post('vendor/removeMultiple','admin\VendorController@removeMultiple'); 

// Product

    Route::get('product', 'admin\ProductController@index');    
    Route::get('product/add','admin\ProductController@add');
    Route::post('product/add','admin\ProductController@adddata');
    Route::get('product/edit/{id}', 'admin\ProductController@edit');
    Route::post('product/edit/{id}', 'admin\ProductController@editdata');
    Route::get('product/remove/{id}','admin\ProductController@remove');
    Route::post('product/removeMultiple','admin\ProductController@removeMultiple');

// Product

    Route::get('product-detail', 'admin\ProductdetailController@index');    
    Route::get('product-detail/add','admin\ProductdetailController@add');
    Route::post('product-detail/add','admin\ProductdetailController@adddata');
    Route::get('product-detail/edit/{id}', 'admin\ProductdetailController@edit');
    Route::post('product-detail/edit/{id}', 'admin\ProductdetailController@editdata');
    Route::get('product-detail/remove/{id}','admin\ProductdetailController@remove');
    Route::post('product-detail/removeMultiple','admin\ProductdetailController@removeMultiple');


// Project

    Route::get('project', 'admin\ProjectController@index');    
    Route::get('project/add','admin\ProjectController@add');
    Route::post('project/add','admin\ProjectController@adddata');
    Route::get('project/edit/{id}', 'admin\ProjectController@edit');
    Route::post('project/edit/{id}', 'admin\ProjectController@editdata');
    Route::get('project/remove/{id}','admin\ProjectController@remove');
    Route::post('project/removeMultiple','admin\ProjectController@removeMultiple');    


// Client

    Route::get('client', 'admin\ClientController@index');    
    Route::get('client/add','admin\ClientController@add');
    Route::post('client/add','admin\ClientController@adddata');
    Route::get('client/edit/{id}', 'admin\ClientController@edit');
    Route::post('client/edit/{id}', 'admin\ClientController@editdata');
    Route::get('client/remove/{id}','admin\ClientController@remove');
    Route::post('client/removeMultiple','admin\ClientController@removeMultiple');  


// Plan

    Route::get('plan', 'admin\PlanController@index');    
    Route::get('plan/add','admin\PlanController@add');
    Route::post('plan/add','admin\PlanController@adddata');
    Route::get('plan/edit/{id}', 'admin\PlanController@edit');
    Route::post('plan/edit/{id}', 'admin\PlanController@editdata');
    Route::get('plan/remove/{id}','admin\PlanController@remove');
    Route::post('plan/removeMultiple','admin\PlanController@removeMultiple');    


// blog

    Route::get('blog', 'admin\BlogController@index');    
    Route::get('blog/add','admin\BlogController@add');
    Route::post('blog/add','admin\BlogController@adddata');
    Route::get('blog/edit/{id}', 'admin\BlogController@edit');
    Route::post('blog/edit/{id}', 'admin\BlogController@editdata');
    Route::get('blog/remove/{id}','admin\BlogController@remove');
    Route::post('blog/removeMultiple','admin\BlogController@removeMultiple');    



// Slider

    Route::get('slider', 'admin\SliderController@index');    
    Route::get('slider/add','admin\SliderController@add');
    Route::post('slider/add','admin\SliderController@adddata');
    Route::get('slider/edit/{id}', 'admin\SliderController@edit');
    Route::post('slider/edit/{id}', 'admin\SliderController@editdata');
    Route::get('slider/remove/{id}','admin\SliderController@remove');
    Route::post('slider/removeMultiple','admin\SliderController@removeMultiple');


// Offer

    Route::get('offer', 'admin\OfferController@index');    
    Route::get('offer/add','admin\OfferController@add');
    Route::post('offer/add','admin\OfferController@adddata');
    Route::get('offer/edit/{id}', 'admin\OfferController@edit');
    Route::post('offer/edit/{id}', 'admin\OfferController@editdata');
    Route::get('offer/remove/{id}','admin\OfferController@remove');
    Route::post('offer/removeMultiple','admin\OfferController@removeMultiple');

// Setting

    Route::get('setting', 'admin\SettingController@index');
    Route::get('setting/edit/{id}', 'admin\SettingController@edit');
    Route::post('setting/edit/{id}', 'admin\SettingController@editdata');


// About us

    Route::get('about', 'admin\AboutController@index');
    Route::get('about/edit/{id}', 'admin\AboutController@edit');
    Route::post('about/edit/{id}', 'admin\AboutController@editdata');

// Privacy

    Route::get('privacy/edit/{id}', 'admin\PagesController@privacyedit');
    Route::post('privacy/edit/{id}', 'admin\PagesController@privacyeditdata');

// Term

    
    Route::get('term/edit/{id}', 'admin\PagesController@termedit');
    Route::post('term/edit/{id}', 'admin\PagesController@termeditdata');

// Security

    
    Route::get('security/edit/{id}', 'admin\PagesController@securityedit');
    Route::post('security/edit/{id}', 'admin\PagesController@securityeditdata');

// About us

    Route::get('whatdo', 'admin\whatdoController@index');
    Route::get('whatdo/edit/{id}', 'admin\whatdoController@edit');
    Route::post('whatdo/edit/{id}', 'admin\whatdoController@editdata');


// category

    Route::get('category', 'admin\CategoryController@index');
    Route::get('category/add', 'admin\CategoryController@add');
    Route::post('category/add', 'admin\CategoryController@adddata');
    Route::get('category/edit/{id}', 'admin\CategoryController@edit');
    Route::post('category/edit/{id}', 'admin\CategoryController@editdata');
    Route::get('category/remove/{id}','admin\CategoryController@remove');
    Route::post('category/removeMultiple','admin\CategoryController@removeMultiple');

//
   

// category

    Route::get('faqs', 'admin\FaqsController@index');
    Route::get('faqs/add', 'admin\FaqsController@add');
    Route::post('faqs/add', 'admin\FaqsController@adddata');
    Route::get('faqs/edit/{id}', 'admin\FaqsController@edit');
    Route::post('faqs/edit/{id}', 'admin\FaqsController@editdata');
    Route::get('faqs/remove/{id}','admin\FaqsController@remove');
    Route::post('faqs/removeMultiple','admin\FaqsController@removeMultiple');
    


// change password

    Route::get('/change-password', 'admin\ChangepasswordController@index');
    Route::post('/change-password','admin\ChangepasswordController@changePassword');

    Route::get('order', 'admin\OrderController@order');
    Route::get('user', 'admin\PagesController@user');
    // Route::get('order/status/{order}', 'admin\OrderController@change_status')->name('order_status');

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/change-city/{city_id}', 'HomeController@change_city');
Route::get('/', 'HomeController@index');  
Route::post('/ajax_request', 'AjaxController@index')->name('ajax-route');
Route::get('/project', 'ProjectController@index'); 
Route::get('/about-us', 'AboutController@index'); 
Route::get('project/{slug:slug}', 'SingleProjectController@index'); 
Route::get('/menu', 'ServiceController@index');
Route::get('service/{slug:slug}', 'SingleServiceController@index');
Route::get('/our-team', 'OurTeamController@index'); 
Route::get('/pages', 'PagesController@index'); 
Route::get('/blog', 'BlogController@index'); 
Route::get('/menu', 'MenuController@index'); 
Route::get('/privacy', 'PagesController@privacy'); 
Route::get('/term', 'PagesController@term'); 
Route::get('/security', 'PagesController@security'); 
Route::get('blog/info/{slug:slug}', 'BlogController@single')->name('bloginfo');
Route::post('/blog/save_comment', 'BlogController@save_comment')->name('save_comment'); 
// Route::get('/category', 'CategoryController@index'); 
Route::get('blog/{category:slug}', 'BlogController@index');
// Route::get('category/{category:slug_category}', 'CategoryController@index');
Route::get('/cost-calculater', 'CostCalculaterController@index'); 
Route::get('/contact', 'ContactController@index'); 
// Route::post('/contact/save', 'ContactController@save')->name('contact');
Route::post('contact/ajax_request', 'AjaxController@contactInquiry')->name('contact-route'); 

Route::get('/menu/{slug:slug}', 'ServiceController@single');

Route::group(['prefix' => 'cart'], function () {
    Route::get('/', 'CartController@index')->name('cart');
    Route::post('add', 'CartController@add');
    Route::post('update', 'CartController@update');
    Route::post('remove', 'CartController@remove');
});
Route::get('/terms-and-conditions', 'HomeController@terms')->name('terms');


Route::post('user_login', 'AjaxController@auth');
Route::post('user_register', 'AjaxController@register');
Route::post('user_verifyotp', 'AjaxController@verifyOtp');
Route::post('user_forgotpass', 'AjaxController@forgot');
Route::post('user_verifyforgototp', 'AjaxController@verifyForgotOtp');
Route::post('user_recoverpass', 'AjaxController@save_password');
Route::post('resend-otp', 'AjaxController@resendOtp');
Route::post('reservation_table', 'AjaxController@reservation');

Route::group(['prefix' => 'checkout_resv'], function () {
    Route::get('/', 'CheckoutresvController@index')->name('checkout-resv');
    Route::post('/', 'CheckoutresvController@save')->name('dopayment2');
    Route::get('thankyou', 'CheckoutresvController@thank_you');
});

Route::group(['prefix' => 'checkout', 'middleware' => 'auth'], function () {
    Route::get('/', 'CheckoutController@index')->name('checkout');
    Route::post('/', 'CheckoutController@save')->name('dopayment');
    Route::get('thank-you', 'CheckoutController@thank_you');
});



Route::group(['prefix' => 'guest'], function () {
    Route::get('/', 'GuestController@index')->name('guest');
    Route::post('/', 'GuestController@save')->name('dopayment1');
    Route::get('thank_you', 'GuestController@thank_you');
});
Route::group(['prefix' => 'ajax'], function () {
    Route::post('send-otp', 'AjaxController@sendOtp');
    Route::post('check-coupon', 'AjaxController@checkCoupon')->middleware('auth');
    Route::post('remove-coupon', 'AjaxController@removeCoupon')->middleware('auth');
    Route::get('/google', 'ContactController@google');
});

Route::group(['prefix' => 'account', 'middleware' => 'auth', 'namespace' => 'account'], function () {
    Route::get('/', 'UserController@profile')->name('profile');
    Route::get('/edit', 'UserController@edit_profile')->name('edit_profile');
    Route::post('/edit', 'UserController@save_profile');
    Route::get('/my-orders', 'OrderController@my_orders')->name('my_orders');
    Route::get('order-info/{order}', 'OrderController@single')->name('order_info');
    Route::post('/save-rating', 'OrderController@save_rating')->name('save_rating');
    Route::get('/change-password', 'UserController@change_password')->name('change_password');
    Route::post('/change-password', 'UserController@save_password');
    Route::get('/logout', 'UserController@logout')->name('logout');
    Route::get('/wishlist', 'OrderController@wishlist')->name('wishlist');
    
    Route::get('address', 'AddressController@list')->name('address');
    Route::get('add_address', 'AddressController@index');
    Route::post('add_address', 'AddressController@add')->name('add_address');
    Route::get('edit_address/{id}', 'AddressController@edit');
    Route::post('edit_address/{id}', 'AddressController@update')->name('edit_address');
    Route::get('delete_address/{id}', 'AddressController@destroy');
});
 




    

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;
// use Illuminate\Routing\Controller as BaseController;
use Illuminate\Http\Request;
use App\model\Client;
use App\model\Plan;
use App\model\Slider;
use App\model\About;
use App\model\Whatdo;
use App\model\Product;
use App\model\Productdetail;
use App\model\Category;
use App\model\Marquee;
use App\model\Pages;
use App\model\Faq;
use App\model\Setting;
use App\model\Offer;
use App\model\Blog;
use App\model\City;



class HomeController extends Controller {
    public function index(Request $request, $cslug = null, $id=1) {
        
        $slider=Slider::latest()->paginate(10);       
    	$term=Pages::findOrFail(2);	  	
    	$about=About::findOrFail(1);	  	
        $whatdo=Whatdo::findOrFail(1);      
    	$setting=Setting::findOrFail(1); 
                
        $offer=Offer::get();        
    	$city=City::get();	  	
    	$faq=Faq::latest()->get();


        $city_id = session()->get('city_session');
        // var_dump($city_id);
        // die;
        if($city_id===null)
        // $cid = City::where('is_default', 1)->get();
    	$city_id = 1;
         // dd($cid);



        $product  =  Product::withCount('p')
        ->with('category','p')
        ->whereHas('vendor', function ($q) use ($city_id) {
            $q->where('city_id', $city_id);
        })
        ->get();
        
        
        // $productdetail = Productdetail::with(['product'])->get();
        // dd($productdetail);
        

        $category =  Category::with(['products'])->has('products')->get();
        
        $blog =  Blog::get();
        $weight = $product;
    	$data = compact('slider','about','whatdo','product','term','faq','setting','offer','category','blog','cslug','city');
    	
    	return view('frontend.inc.homepage' ,$data);
    }

    public function change_city($city_id) {

        session()->put('city_session', $city_id);

        return redirect()->back()->with('success', 'city changed');
    }
}

resources/views/backend/inc/product/index.blade.php
 @extends('backend.layout.master')

@section('title','product')

@section('contant')
		<div class="content-main-block  mrg-t-40">
    <div class="admin-create-btn-block">
      <a href="{{ url('admin-control/product/add') }}" class="btn btn-danger btn-md">Add Product</a>
      <!-- Delete Modal -->
      <a type="button" class="btn btn-danger btn-md" data-toggle="modal" data-target="#bulk_delete"><i class="material-icons left">delete</i> Delete Selected</a>
         
      <!-- Modal -->
      <div id="bulk_delete" class="delete-modal modal fade" role="dialog">
        <div class="modal-dialog modal-sm">
          <!-- Modal content-->
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal">&times;</button>
              <div class="delete-icon"></div>
            </div>
            <div class="modal-body text-center">
              <h4 class="modal-heading">Are You Sure ?</h4>
              <p>Do you really want to delete these records? This process cannot be undone.</p>
            </div>
            <div class="modal-footer">
              {!! Form::open(['method' => 'POST', 'url' => url('admin-control/product/removeMultiple') ,'id' => 'bulk_delete_form']) !!}
                <button type="reset" class="btn btn-gray translate-y-3" data-dismiss="modal">No</button>
                <button type="submit" class="btn btn-danger">Yes</button>
              {!! Form::close() !!}
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="content-block box-body">
      <table id="full_detail_table" class="table table-hover table-responsive">
        <thead>
          <tr class="table-heading-row">
            <th>
              <div class="inline">
                <input id="checkboxAll" type="checkbox" class="filled-in" name="checked[]" value="all" id="checkboxAll">
                <label for="checkboxAll" class="material-checkbox"></label>
              </div>
            #</th>
            <th>Image </th>
            <th>Title</th>
            <th>slug</th>
            <th>Category</th>
            <th>Actions</th>
          </tr>
        </thead>
          @if (isset($product))
          <tbody>
            @foreach ($product as $key => $item)
              <tr>
                <td>
                @if(!$item->p_count)
                  <div class="inline">
                    <input type="checkbox" form="bulk_delete_form" class="filled-in material-checkbox-input" name="checked[]" value="{{$item->id}}" id="checkbox{{$item->id}}">
                    <label for="checkbox{{$item->id}}" class="material-checkbox"></label>
                  </div>
                  {{$key+1}}
                  @else
                  It is used
                  @endif
                </td>
                <td>
                  @if($item->icon != null)
                    <i class="fa {{$item->icon}}" style="font-size: 30px;"></i>
                  @elseif($item->image != null)
                    <img src="{{ asset('imgs/product/'.$item->image) }}" class="img-responsive" width="80" alt="image">
                  @else
                    N/A  
                  @endif
                </td>
                <td>{{$item->title}}</td>
                <td>{{$item->slug}}</td>
                <td>{{ $item->category ? $item->category->title : 'N/A'}}</td>
                <td>
                  <div class="admin-table-action-block">
                    <a href="{{url('admin-control/product/edit/'.$item->id)}}" data-toggle="tooltip" data-original-title="Edit" class="btn-info btn-floating"><i class="material-icons">mode_edit</i></a>
                    <!-- Delete Modal -->
                    @if(!$item->p_count)
                    <button type="button" class="btn-danger btn-floating" data-toggle="modal" data-target="#{{$item->id}}deleteModal"><i class="material-icons">delete</i> </button>
                    @else
                    @endif
                    <!-- Modal -->
                    <div id="{{$item->id}}deleteModal" class="delete-modal modal fade" role="dialog">
                      <div class="modal-dialog modal-sm">
                        <!-- Modal content-->
                        <div class="modal-content">
                          <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                            <div class="delete-icon"></div>
                          </div>
                          <div class="modal-body text-center">
                            <h4 class="modal-heading">Are You Sure ?</h4>
                            <p>Do you really want to delete these records? This process cannot be undone.</p>
                          </div>
                          <div class="modal-footer">
                            {!! Form::open(['url' => url('admin-control/product/remove/'.$item->id),'method' => 'GET', $item->id]) !!}
                                <button type="reset" class="btn btn-gray translate-y-3" data-dismiss="modal">No</button>
                                <button type="submit" class="btn btn-danger">Yes</button>
                            {!! Form::close() !!}
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </td>
              </tr>
            @endforeach
          </tbody>
        @endif  
      </table>
    </div>
  </div>
@stop