routes/admin.php
// Logout

Route::group(['prefix' => 'admin-control', 'middleware' => 'auth'], function() {
    Route::get( 'logout', 'admin\UserController@logout' );
    Route::get( 'dashboard', ['as' => 'home', 'uses' => 'admin\DashboardController@index' ]  );

// dashboard

    Route::get('dashboard','admin\DashboardController@index');
    Route::get('/inquiry','admin\InquiryController@index');
    Route::get('inquiry/remove/{id}','admin\InquiryController@remove');
    Route::post('inquiry/removeMultiple','admin\InquiryController@removeMultiple');
    
Route::get('/clear-cache', function() {
    $exitCode = Artisan::call('cache:clear');
    return 'clearede';
});



// Marquee-img

    Route::get('marquee-img', 'admin\MarqueeController@index');    
    Route::get('marquee-img/add','admin\MarqueeController@add');
    Route::post('marquee-img/add','admin\MarqueeController@adddata');
    Route::get('marquee-img/edit/{id}', 'admin\MarqueeController@edit');
    Route::post('marquee-img/edit/{id}', 'admin\MarqueeController@editdata');
    Route::get('marquee-img/remove/{id}','admin\MarqueeController@remove');
    Route::post('marquee-img/removeMultiple','admin\MarqueeController@removeMultiple');


// Unit

    Route::get('unit', 'admin\UnitController@index');    
    Route::get('unit/add','admin\UnitController@add');
    Route::post('unit/add','admin\UnitController@adddata');
    Route::get('unit/edit/{id}', 'admin\UnitController@edit');
    Route::post('unit/edit/{id}', 'admin\UnitController@editdata');
    Route::get('unit/remove/{id}','admin\UnitController@remove');
    Route::post('unit/removeMultiple','admin\UnitController@removeMultiple'); 

// Unit

    Route::get('coupon', 'admin\CouponController@index');    
    Route::get('coupon/add','admin\CouponController@add');
    Route::post('coupon/add','admin\CouponController@adddata');
    Route::get('coupon/edit/{id}', 'admin\CouponController@edit');
    Route::post('coupon/edit/{id}', 'admin\CouponController@editdata');
    Route::get('coupon/remove/{id}','admin\CouponController@remove');
    Route::post('coupon/removeMultiple','admin\CouponController@removeMultiple'); 

// City

    Route::get('city', 'admin\CityController@index');    
    Route::get('city/add','admin\CityController@add');
    Route::post('city/add','admin\CityController@adddata');
    Route::get('city/edit/{id}', 'admin\CityController@edit');
    Route::post('city/edit/{id}', 'admin\CityController@editdata');
    Route::get('city/remove/{id}','admin\CityController@remove');
    Route::post('city/removeMultiple','admin\CityController@removeMultiple'); 

// Vendor

    Route::get('vendor', 'admin\VendorController@index');    
    Route::get('vendor/add','admin\VendorController@add');
    Route::post('vendor/add','admin\VendorController@adddata');
    Route::get('vendor/edit/{id}', 'admin\VendorController@edit');
    Route::post('vendor/edit/{id}', 'admin\VendorController@editdata');
    Route::get('vendor/remove/{id}','admin\VendorController@remove');
    Route::post('vendor/removeMultiple','admin\VendorController@removeMultiple'); 

// Product

    Route::get('product', 'admin\ProductController@index');    
    Route::get('product/add','admin\ProductController@add');
    Route::post('product/add','admin\ProductController@adddata');
    Route::get('product/edit/{id}', 'admin\ProductController@edit');
    Route::post('product/edit/{id}', 'admin\ProductController@editdata');
    Route::get('product/remove/{id}','admin\ProductController@remove');
    Route::post('product/removeMultiple','admin\ProductController@removeMultiple');

// Product

    Route::get('product-detail', 'admin\ProductdetailController@index');    
    Route::get('product-detail/add','admin\ProductdetailController@add');
    Route::post('product-detail/add','admin\ProductdetailController@adddata');
    Route::get('product-detail/edit/{id}', 'admin\ProductdetailController@edit');
    Route::post('product-detail/edit/{id}', 'admin\ProductdetailController@editdata');
    Route::get('product-detail/remove/{id}','admin\ProductdetailController@remove');
    Route::post('product-detail/removeMultiple','admin\ProductdetailController@removeMultiple');


// Project

    Route::get('project', 'admin\ProjectController@index');    
    Route::get('project/add','admin\ProjectController@add');
    Route::post('project/add','admin\ProjectController@adddata');
    Route::get('project/edit/{id}', 'admin\ProjectController@edit');
    Route::post('project/edit/{id}', 'admin\ProjectController@editdata');
    Route::get('project/remove/{id}','admin\ProjectController@remove');
    Route::post('project/removeMultiple','admin\ProjectController@removeMultiple');    


// Client

    Route::get('client', 'admin\ClientController@index');    
    Route::get('client/add','admin\ClientController@add');
    Route::post('client/add','admin\ClientController@adddata');
    Route::get('client/edit/{id}', 'admin\ClientController@edit');
    Route::post('client/edit/{id}', 'admin\ClientController@editdata');
    Route::get('client/remove/{id}','admin\ClientController@remove');
    Route::post('client/removeMultiple','admin\ClientController@removeMultiple');  


// Plan

    Route::get('plan', 'admin\PlanController@index');    
    Route::get('plan/add','admin\PlanController@add');
    Route::post('plan/add','admin\PlanController@adddata');
    Route::get('plan/edit/{id}', 'admin\PlanController@edit');
    Route::post('plan/edit/{id}', 'admin\PlanController@editdata');
    Route::get('plan/remove/{id}','admin\PlanController@remove');
    Route::post('plan/removeMultiple','admin\PlanController@removeMultiple');    


// blog

    Route::get('blog', 'admin\BlogController@index');    
    Route::get('blog/add','admin\BlogController@add');
    Route::post('blog/add','admin\BlogController@adddata');
    Route::get('blog/edit/{id}', 'admin\BlogController@edit');
    Route::post('blog/edit/{id}', 'admin\BlogController@editdata');
    Route::get('blog/remove/{id}','admin\BlogController@remove');
    Route::post('blog/removeMultiple','admin\BlogController@removeMultiple');    



// Slider

    Route::get('slider', 'admin\SliderController@index');    
    Route::get('slider/add','admin\SliderController@add');
    Route::post('slider/add','admin\SliderController@adddata');
    Route::get('slider/edit/{id}', 'admin\SliderController@edit');
    Route::post('slider/edit/{id}', 'admin\SliderController@editdata');
    Route::get('slider/remove/{id}','admin\SliderController@remove');
    Route::post('slider/removeMultiple','admin\SliderController@removeMultiple');


// Offer

    Route::get('offer', 'admin\OfferController@index');    
    Route::get('offer/add','admin\OfferController@add');
    Route::post('offer/add','admin\OfferController@adddata');
    Route::get('offer/edit/{id}', 'admin\OfferController@edit');
    Route::post('offer/edit/{id}', 'admin\OfferController@editdata');
    Route::get('offer/remove/{id}','admin\OfferController@remove');
    Route::post('offer/removeMultiple','admin\OfferController@removeMultiple');

// Setting

    Route::get('setting', 'admin\SettingController@index');
    Route::get('setting/edit/{id}', 'admin\SettingController@edit');
    Route::post('setting/edit/{id}', 'admin\SettingController@editdata');


// About us

    Route::get('about', 'admin\AboutController@index');
    Route::get('about/edit/{id}', 'admin\AboutController@edit');
    Route::post('about/edit/{id}', 'admin\AboutController@editdata');

// Privacy

    Route::get('privacy/edit/{id}', 'admin\PagesController@privacyedit');
    Route::post('privacy/edit/{id}', 'admin\PagesController@privacyeditdata');

// Term

    
    Route::get('term/edit/{id}', 'admin\PagesController@termedit');
    Route::post('term/edit/{id}', 'admin\PagesController@termeditdata');

// Security

    
    Route::get('security/edit/{id}', 'admin\PagesController@securityedit');
    Route::post('security/edit/{id}', 'admin\PagesController@securityeditdata');

// About us

    Route::get('whatdo', 'admin\whatdoController@index');
    Route::get('whatdo/edit/{id}', 'admin\whatdoController@edit');
    Route::post('whatdo/edit/{id}', 'admin\whatdoController@editdata');


// category

    Route::get('category', 'admin\CategoryController@index');
    Route::get('category/add', 'admin\CategoryController@add');
    Route::post('category/add', 'admin\CategoryController@adddata');
    Route::get('category/edit/{id}', 'admin\CategoryController@edit');
    Route::post('category/edit/{id}', 'admin\CategoryController@editdata');
    Route::get('category/remove/{id}','admin\CategoryController@remove');
    Route::post('category/removeMultiple','admin\CategoryController@removeMultiple');

//
   

// category

    Route::get('faqs', 'admin\FaqsController@index');
    Route::get('faqs/add', 'admin\FaqsController@add');
    Route::post('faqs/add', 'admin\FaqsController@adddata');
    Route::get('faqs/edit/{id}', 'admin\FaqsController@edit');
    Route::post('faqs/edit/{id}', 'admin\FaqsController@editdata');
    Route::get('faqs/remove/{id}','admin\FaqsController@remove');
    Route::post('faqs/removeMultiple','admin\FaqsController@removeMultiple');
    


// change password

    Route::get('/change-password', 'admin\ChangepasswordController@index');
    Route::post('/change-password','admin\ChangepasswordController@changePassword');

    Route::get('order', 'admin\OrderController@order');
    Route::get('user', 'admin\PagesController@user');
    // Route::get('order/status/{order}', 'admin\OrderController@change_status')->name('order_status');
    // Route::get('order/status/{id}', 'admin\OrderController@change_status')->name('order_status');
    Route::get('order/{list}', 'admin\OrderController@infopage');
    Route::get('/order/status/{customer}', 'admin\OrderController@change_status')->name('order_status');
    
    Route::get('send-mail', 'admin\InquiryController@mail');
	Route::post('send-mail', 'admin\InquiryController@mailsend');

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/change-city/{city_id}', 'HomeController@change_city');
Route::get('/', 'HomeController@index');  
Route::post('/ajax_request', 'AjaxController@index')->name('ajax-route');
Route::get('/project', 'ProjectController@index'); 
Route::get('/about-us', 'AboutController@index'); 
Route::get('project/{slug:slug}', 'SingleProjectController@index'); 
Route::get('/menu', 'ServiceController@index');
Route::get('service/{slug:slug}', 'SingleServiceController@index');
Route::get('/our-team', 'OurTeamController@index'); 
Route::get('/pages', 'PagesController@index'); 
Route::get('/blog', 'BlogController@index'); 
Route::get('/menu', 'MenuController@index'); 
Route::get('/privacy', 'PagesController@privacy'); 
Route::get('/term', 'PagesController@term'); 
Route::get('/security', 'PagesController@security'); 
Route::get('blog/info/{slug:slug}', 'BlogController@single')->name('bloginfo');
Route::post('/blog/save_comment', 'BlogController@save_comment')->name('save_comment'); 
// Route::get('/category', 'CategoryController@index'); 
Route::get('blog/{category:slug}', 'BlogController@index');
// Route::get('category/{category:slug_category}', 'CategoryController@index');
Route::get('/cost-calculater', 'CostCalculaterController@index'); 
Route::get('/contact', 'ContactController@index'); 
// Route::post('/contact/save', 'ContactController@save')->name('contact');
Route::post('contact/ajax_request', 'AjaxController@contactInquiry')->name('contact-route'); 

Route::get('/menu/{slug:slug}', 'ServiceController@single');

Route::group(['prefix' => 'cart'], function () {
    Route::get('/', 'CartController@index')->name('cart');
    Route::post('add', 'CartController@add');
    Route::post('update', 'CartController@update');
    Route::post('remove', 'CartController@remove');
});
Route::get('/terms-and-conditions', 'HomeController@terms')->name('terms');


Route::post('user_login', 'AjaxController@auth');
Route::post('user_register', 'AjaxController@register');
Route::post('user_verifyotp', 'AjaxController@verifyOtp');
Route::post('user_forgotpass', 'AjaxController@forgot');
Route::post('user_verifyforgototp', 'AjaxController@verifyForgotOtp');
Route::post('user_recoverpass', 'AjaxController@save_password');
Route::post('resend-otp', 'AjaxController@resendOtp');
Route::post('reservation_table', 'AjaxController@reservation');

Route::group(['prefix' => 'checkout_resv'], function () {
    Route::get('/', 'CheckoutresvController@index')->name('checkout-resv');
    Route::post('/', 'CheckoutresvController@save')->name('dopayment2');
    Route::get('thankyou', 'CheckoutresvController@thank_you');
});

Route::group(['prefix' => 'checkout', 'middleware' => 'auth'], function () {
    Route::get('/', 'CheckoutController@index')->name('checkout');
    Route::post('/', 'CheckoutController@save')->name('dopayment');
    Route::get('thank-you', 'CheckoutController@thank_you');
});



Route::group(['prefix' => 'guest'], function () {
    Route::get('/', 'GuestController@index')->name('guest');
    Route::post('/', 'GuestController@save')->name('dopayment1');
    Route::get('thank_you', 'GuestController@thank_you');
});
Route::group(['prefix' => 'ajax'], function () {
    Route::post('send-otp', 'AjaxController@sendOtp');
    Route::post('check-coupon', 'AjaxController@checkCoupon')->middleware('auth');
    Route::post('remove-coupon', 'AjaxController@removeCoupon')->middleware('auth');
    Route::get('/google', 'ContactController@google');
});

Route::group(['prefix' => 'account', 'middleware' => 'auth', 'namespace' => 'account'], function () {
    Route::get('/', 'UserController@profile')->name('profile');
    Route::get('/edit', 'UserController@edit_profile')->name('edit_profile');
    Route::post('/edit', 'UserController@save_profile');
    Route::get('/my-orders', 'OrderController@my_orders')->name('my_orders');
    Route::get('order-info/{order}', 'OrderController@single')->name('order_info');
    Route::post('/save-rating', 'OrderController@save_rating')->name('save_rating');
    Route::get('/change-password', 'UserController@change_password')->name('change_password');
    Route::post('/change-password', 'UserController@save_password');
    Route::get('/logout', 'UserController@logout')->name('logout');
    Route::get('/wishlist', 'OrderController@wishlist')->name('wishlist');
    
    Route::get('address', 'AddressController@list')->name('address');
    Route::get('add_address', 'AddressController@index');
    Route::post('add_address', 'AddressController@add')->name('add_address');
    Route::get('edit_address/{id}', 'AddressController@edit');
    Route::post('edit_address/{id}', 'AddressController@update')->name('edit_address');
    Route::get('delete_address/{id}', 'AddressController@destroy');
});
 




    

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;
use App\model\Category;
use App\model\Blog;
use App\model\Setting;

use Illuminate\Routing\Controller as BaseController;

class CategoryController extends BaseController {
    public function index() {
        $category1   = Category::latest()->get();
        $latestblog = Blog::latest()->paginate(15);
        $setting= Setting::findOrFail(1);
        $list = compact('latestblog','category1','setting');
    	return view('frontend.inc.category', $list);
    }
}

app/Http/Controllers/ServiceController.php
<?php

namespace App\Http\Controllers;
use Illuminate\Http\Request;
use App\model\Category;
use App\model\Product;
use App\model\Setting;


use Illuminate\Routing\Controller as BaseController;

class ServiceController extends BaseController {

    public function index(Request $request, $cslug = null)
    {
        $categoryInfo = [];
        // if (!empty($cslug)) {
        //     $categoryInfo   = Category::where('slug', $cslug)->where('category_is_deleted', 'N')->select('id')->first();
        // }

        $query = Product::with(['cat']);
        if (!empty($categoryInfo->id)) {
            $query->where('category_id', $categoryInfo->id);
        }
        if( !empty( $request->s ) ) {
            $query->where('name', 'LIKE', '%'.$request->s.'%');
        }

        

        $products   = $query->paginate(1000);

        // Get All Categories
        $categories     = Category::withCount('products')->has('products')->where('category_is_deleted', 'N')->where('parent', null)->orderBy('title', 'ASC')->get();

        $data = compact('categoryInfo', 'products', 'categories', 'cslug');
        return view('frontend.inc.service', $data);
    }

    public function single( Product $slug  )
    {
        $setting = Setting::findOrFail(1);
        $data1 = Product::where('id','!=', $slug->id)->paginate(3)->toArray();
        $data    = compact('setting','slug','data1');
        return view('frontend.inc.menu_single',$data);
    }
}

resources/views/backend/inc/category/add.blade.php
@extends('backend.layout.master')

@section('title','category')

@section('contant')
<div class="admin-form-main-block mrgn-t-40">
    <h4 class="admin-form-text"><a href="{{url('admin/category')}}" data-toggle="tooltip" data-original-title="Go back" class="btn-floating"><i class="material-icons">reply</i></a> Add Category</h4> 
    {!! Form::open(['method' => 'POST', 'files' => true]) !!}
      <div class="row admin-form-block z-depth-1">
        <div class="col-md-6">
          <div class="form-group{{ $errors->has('title') ? ' has-error' : '' }}">
              {!! Form::label('title', 'Category Name / Title') !!} - 
              {!! Form::text('title', null, ['class' => 'form-control']) !!}
              <small class="text-danger">{{ $errors->first('title') }}</small>
          </div> 
		  
		  
		   <div class="form-group{{ $errors->has('slug') ? ' has-error' : '' }}">
              {!! Form::label('slug', 'Category Slug') !!} - <p class="inline info"></p>
              {!! Form::text('slug', null, ['class' => 'form-control']) !!}
              <small class="text-danger">{{ $errors->first('slug') }}</small>
          </div> 
		  
		  
     <!--     <div class="form-group{{ $errors->has('icon') ? ' has-error' : '' }} currency-symbol-block">
            {!! Form::label('icon', 'Category Icon / Symbol') !!}
            <p class="inline info"> - Please select catgeory symbol or category image</p>
              <div class="input-group">
                {!! Form::text('icon', null, ['class' => 'form-control category-icon-picker']) !!}
                <span class="input-group-addon simple-input"><i class="glyphicon glyphicon-th-large"></i></span>
              </div>
            <small class="text-danger">{{ $errors->first('icon') }}</small>
          </div>
		  -->
		  
       
          <!--<div class="form-group{{ $errors->has('image_i') ? ' has-error' : '' }} input-file-block">-->
          <!--  {!! Form::label('image_i', 'Category Image') !!} -->
          <!--  {!! Form::file('image_i', ['class' => 'input-file', 'id'=>'image_i']) !!}-->
          <!--  <label for="image_i" class="btn btn-danger js-labelFile" data-toggle="tooltip" data-original-title="Category Image">-->
          <!--    <i class="icon fa fa-check"></i>-->
          <!--    <span class="js-fileName">Choose a File</span>-->
          <!--  </label>-->
          <!--  <p class="info">Choose custom image</p>-->
          <!--  <small class="text-danger">{{ $errors->first('image_i') }}</small>-->
          <!--</div> -->
          <div class="form-group{{ $errors->has('category_is_deleted') ? ' has-error' : '' }} switch-main-block">
            <div class="row">
              <div class="col-xs-4">
                {!! Form::label('category_is_deleted', 'Status') !!}
              </div>
              <div class="col-xs-5 pad-0">
                <label class="switch">                
                  {!! Form::checkbox('category_is_deleted', 1, 1, ['class' => 'checkbox-switch']) !!}
                  <span class="slider round"></span>
                </label>
              </div>
            </div>
            <div class="col-xs-12">
              <small class="text-danger">{{ $errors->first('category_is_deleted') }}</small>
            </div>
          </div>          
          <div class="btn-group pull-right">
            <button type="reset" class="btn btn-info">Reset</button>
            <button type="submit" class="btn btn-success">Create</button>
          </div>
          <div class="clear-both"></div>
        </div>  
      </div>
    {!! Form::close() !!}
  </div>
@stop
		    	
				    

			
		
	

resources/views/backend/inc/category/edit.blade.php
@extends('backend.layout.master')

@section('title','category')

@section('contant')
<div class="admin-form-main-block mrgn-t-40">
    <h4 class="admin-form-text"><a href="{{url('admin/category')}}" data-toggle="tooltip" data-original-title="Go back" class="btn-floating"><i class="material-icons">reply</i></a> Edit Category</h4> 
    {!! Form::model(['method' => 'PATCH','files' => true]) !!}
      <div class="row admin-form-block z-depth-1">
        <div class="col-md-6">
          <div class="form-group{{ $errors->has('title') ? ' has-error' : '' }}">
              {!! Form::label('title', 'Category Name / Title') !!} - 
              {!! Form::text('title', null, ['class' => 'form-control']) !!}
              <small class="text-danger">{{ $errors->first('title') }}</small>
          </div>
		  
		  
		  <div class="form-group{{ $errors->has('slug') ? ' has-error' : '' }}">
              {!! Form::label('slug', 'Category Slug') !!} - <p class="inline info"></p>
              {!! Form::text('slug', null, ['class' => 'form-control']) !!}
              <small class="text-danger">{{ $errors->first('slug') }}</small>
          </div> 
		  
		  
		  
		  
		  
      <!--    <div class="form-group{{ $errors->has('icon') ? ' has-error' : '' }} currency-symbol-block">
            {!! Form::label('icon', 'Category Icon / Symbol') !!}
            <p class="inline info"> - Please select catgeory symbol or category image</p>
              <div class="input-group">
                {!! Form::text('icon', null, ['class' => 'form-control category-icon-picker']) !!}
                <span class="input-group-addon simple-input"><i class="glyphicon glyphicon-user"></i></span>
              </div>
            <small class="text-danger">{{ $errors->first('icon') }}</small>
          </div>
		  --->
		  
        
          <!--<div class="form-group{{ $errors->has('image_i') ? ' has-error' : '' }} input-file-block">-->
          <!--  {!! Form::label('image_i', 'Category Image') !!} -->
          <!--  {!! Form::file('image_i', ['class' => 'input-file', 'id'=>'image_i']) !!}-->
          <!--  <label for="image_i" class="btn btn-danger js-labelFile" data-toggle="tooltip" data-original-title="Category Image">-->
          <!--    <i class="icon fa fa-check"></i>-->
          <!--    <span class="js-fileName">Choose a File</span>-->
          <!--  </label>-->
          <!--  <p class="info">Choose custom image</p>-->
          <!--  <small class="text-danger">{{ $errors->first('image_i') }}</small>-->
          <!--</div> -->
          <div class="form-group{{ $errors->has('is_active') ? ' has-error' : '' }} switch-main-block">
            <div class="row">
              <div class="col-xs-4">
                {!! Form::label('is_active', 'Status') !!}
              </div>
              <div class="col-xs-5 pad-0">
                <label class="switch">                
                  {!! Form::checkbox('is_active', null, null, ['class' => 'checkbox-switch']) !!}
                  <span class="slider round"></span>
                </label>
              </div>
            </div>
            <div class="col-xs-12">
              <small class="text-danger">{{ $errors->first('is_active') }}</small>
            </div>
          </div>         
          <div class="btn-group pull-right">
            <button type="submit" class="btn btn-success">Update</button>
          </div>
          <div class="clear-both"></div>
        </div>  
      </div>
    {!! Form::close() !!}
  </div>
@stop
		    	
				    

			
		
	

resources/views/backend/inc/category/index.blade.php
 @extends('backend.layout.master')

@section('title','category')

@section('contant')
		<div class="content-main-block  mrg-t-40">
    <div class="admin-create-btn-block">
      <a href="{{ url('admin-control/category/add') }}" class="btn btn-danger btn-md">Add Category</a>
      <!-- Delete Modal -->
      <a type="button" class="btn btn-danger btn-md" data-toggle="modal" data-target="#bulk_delete"><i class="material-icons left">delete</i> Delete Selected</a>
         
      <!-- Modal -->
      <div id="bulk_delete" class="delete-modal modal fade" role="dialog">
        <div class="modal-dialog modal-sm">
          <!-- Modal content-->
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal">&times;</button>
              <div class="delete-icon"></div>
            </div>
            <div class="modal-body text-center">
              <h4 class="modal-heading">Are You Sure ?</h4>
              <p>Do you really want to delete these records? This process cannot be undone.</p>
            </div>
            <div class="modal-footer">
              {!! Form::open(['method' => 'POST', 'url' => url('admin-control/category/removeMultiple') ,'id' => 'bulk_delete_form']) !!}
                <button type="reset" class="btn btn-gray translate-y-3" data-dismiss="modal">No</button>
                <button type="submit" class="btn btn-danger">Yes</button>
              {!! Form::close() !!}
            </div>
          </div>
        </div>
      </div>
      
    </div>
    <div class="content-block box-body">
      <table id="full_detail_table" class="table table-hover table-responsive">
        <thead>
          <tr class="table-heading-row">
            <th>
              <div class="inline">
                <input id="checkboxAll" type="checkbox" class="filled-in check" name="checked[]" value="all" id="checkboxAll">
                <label for="checkboxAll" class="material-checkbox"></label>
              </div>
            #</th>
            <!--<th>Image </th>-->
            <th>Title</th>
            <th>slug</th>
            <th>Status</th>
            <th>Actions</th>
          </tr>
        </thead>
          @if (isset($category))
          <tbody>
            @foreach ($category as $key => $item)
              <tr>
                <td>
                @if(!$item->products_count)
                  <div class="inline">
                    <input type="checkbox" form="bulk_delete_form" class="filled-in material-checkbox-input" name="checked[]" value="{{$item->id}}" id="checkbox{{$item->id}}">
                    <label for="checkbox{{$item->id}}" class="material-checkbox"></label>
                  </div>
                  {{$key+1}}
                @else
                    -
                @endif
                </td>
                <!--<td>-->
                <!--  @if($item->icon != null)-->
                <!--    <i class="fa {{$item->icon}}" style="font-size: 30px;"></i>-->
                <!--  @elseif($item->image != null)-->
                <!--    <img src="{{ asset('imgs/category/'.$item->image_i) }}" class="img-responsive" width="80" alt="{{$item->title}}">-->
                <!--  @else-->
                <!--    N/A  -->
                <!--  @endif-->
                <!--</td>-->
                <td>{{$item->title}}</td>
                <td>{{$item->slug}}</td>
                <td>{{$item->category_is_deleted == 'N' ? 'Active' : 'Deactive'}}</td>
                <td>
                  <div class="admin-table-action-block">
                    <a href="{{url('admin-control/category/edit',$item->id)}}" data-toggle="tooltip" data-original-title="Edit" class="btn-info btn-floating"><i class="material-icons">mode_edit</i></a>
                    <!-- Delete Modal -->
                    @if(!$item->products_count)
                    <button type="button" class="btn-danger btn-floating" data-toggle="modal" data-target="#{{$item->id}}deleteModal"><i class="material-icons">delete</i> </button>
                    @else
                    @endif
                    <!-- Modal -->
                    <div id="{{$item->id}}deleteModal" class="delete-modal modal fade" role="dialog">
                      <div class="modal-dialog modal-sm">
                        <!-- Modal content-->
                        <div class="modal-content">
                          <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                            <div class="delete-icon"></div>
                          </div>
                          <div class="modal-body text-center">
                            <h4 class="modal-heading">Are You Sure ?</h4>
                            <p>Do you really want to delete these records? This process cannot be undone.</p>
                          </div>
                          <div class="modal-footer">
                            {!! Form::open(['url' => url('admin-control/category/remove/'.$item->id),'method' => 'GET', $item->id]) !!}
                                <button type="reset" class="btn btn-gray translate-y-3" data-dismiss="modal">No</button>
                                <button type="submit" class="btn btn-danger">Yes</button>
                            {!! Form::close() !!}
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </td>
              </tr>
            @endforeach
          </tbody>
        @endif  
      </table>
    </div>
  </div>
@stop